services:
  - type: web
    name: multiplayer-chess
    env: node
    buildCommand: |
      npm install
      cd client
      npm install
      npm run build
      cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
